### ISSUE TITLE
handlr open "https://google.com" causes flatpak firefox to try to open "file://$(pwd)/%u"

### ISSUE THREAD

**Issue by TiZ-HugLife** [chmln/handlr#1]
Hiya. Got Firefox installed as a flatpak, and when trying to use this nifty-looking utility to open a URL, it does correctly open Firefox, but it tries to load the page "file://$(pwd)/%u" and fails. Other applications open URLs in firefox just fine.

What do you need from me to diagnose and fix this?

EDIT: Here's the exec line of the desktop file:

`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=firefox --file-forwarding org.mozilla.firefox @@u %u @@`

Is your utility not correctly handling the %u specifier?

**Comment by chmln** [comment]
Fixed in v0.2.1 out right now.

Thanks @TiZ-EX1 :)

**Comment by TiZ-HugLife** [comment]
Awesome, thank YOU! Confirmed the fix works. :)
