### ISSUE TITLE
MagicError: File 5.39 supports only version 16 magic files. 

### ISSUE THREAD

**Issue by cking** [chmln/handlr#12]
In lots of applications I get the following error message when trying to open a file:

> MagicError: File 5.39 supports only version 16 magic files. '/-tmp/.mime_detective_magic.mgc' is version 14

I am using latest Arch [with the xdg-utils replacer]. What am I doing wrong?
If there is anything I can help or provide with additional help, I'd be happy to

**Comment by chmln** [comment]
@cking you're using an outdated version, just upgrade to the latest one and all your problems will disappear :airplane:

**Comment by cking** [comment]
AUR has only handlr-bin in version 0.4.5-1 - no other version is available :(
```
:: Querying AUR...
Repository      : aur
Name            : handlr-bin
Keywords        : mime  rust  xdg-open  xdg-utils
Version         : 0.4.5-1
Description     : Powerful alternative to xdg-utils written in Rust
URL             : https://github.com/chmln/handlr
AUR URL         : https://aur.archlinux.org/packages/handlr-bin
Groups          : None
Licenses        : unknown
Provides        : None
Depends On      : None
Make Deps       : None
Check Deps      : None
Optional Deps   : None
Conflicts With  : None
Maintainer      : chmln
Votes           : 2
Popularity      : 1.492381
First Submitted : Wed 20 May 2020 06:43:49 AM CEST
Last Modified   : Sun 21 Jun 2020 03:28:35 AM CEST
Out-of-date     : No
```

**Comment by chmln** [comment]
@cking I suggested upgrading because that error looks like one from the `mime-detective` dependency which handlr had until recent one or two versions.

What's the output of the following ?

```sh
which handlr
handlr --version
```

**Comment by cking** [comment]
```
❯ which handlr ; handlr --version
/usr/bin/handlr
handlr 0.4.3
```

**Comment by chmln** [comment]
@cking so the latest version is `v0.4.5` :) Could you try reinstalling and see if that fixes your issue?

**Comment by cking** [comment]
i did that 3 times.
2 times reinstalling and one time uninstalling and then installing again.
the 0.4.5 package installs 0.4.3 for me

**Comment by chmln** [comment]
@cking must be some issue with an AUR helper. Here's the package https://aur.archlinux.org/packages/handlr-bin 

I manually downloaded the binary and verified that it outputs the correct version.
![image](https://user-images.githubusercontent.com/11352152/86519441-c3126580-be08-11ea-9fd6-a7a5fed8f245.png)

I could suggest using the `yay` AUR helper. 

If somehow that doesn't help either, you can try git-cloning `https://aur.archlinux.org/handlr-bin.git` and running `makepkg -si`

**Comment by cking** [comment]
i am using yay

**Comment by cking** [comment]
well now i got 0.4.5, not sure why yay said it downloaded .4.5 but gave me .4.3
