### ISSUE TITLE
Add the MIT license file to the repository and a tagged release

### ISSUE THREAD

**Issue by nilium** [chmln/handlr#16]
Currently the only indication of what license handlr is under is in the cargo.toml's line stating it's MIT-licensed. This is mostly a bookkeeping thing, but adding a license text file (as COPYING, LICENSE.txt, or other accepted names) helps a few things:

- Makes it easy to see the license at a glance. This helps folks who are selective about the licenses of the software they use.
- GitHub can detect the license file and indicate in the sidebar that it's MIT-licensed (and point users to the license file).
- Folks packaging handlr can provide a copy of the license and copyright notice (because of the second paragraph in the MIT license), allowing them to provide packaged copies of handlr and keep with the spirit of the license.

In particular, I'm running into the last case. In order to package handlr for Void Linux, I need a tagged release of handlr containing the license text so I can package the license with the executable. I don't know that you'd want to tag a release just for the license, but getting a license file into a release would allow me to move forward on packaging handlr for folks to use.

**Comment by chmln** [comment]
@nilium sounds good. I will make a release with the license soon.

**Comment by chmln** [comment]
Added in v0.6.1
