### ISSUE TITLE
Consider switching to xdg-mime

### ISSUE THREAD

**Issue by ebassi** [chmln/handlr#2]
The mime-db crate uses a hard-coded list of globs/MIME type mappings; the mime-sniffer crate uses its own list of magic matchers. This means that every time a new MIME type is added, both crates need to be updated, and thus any dependent crate or application needs to be updated as well.

Most modern Linux/Unix-like OSes provide on the [shared-mime-info](https://freedesktop.org/wiki/Specifications/shared-mime-info-spec/) database for applications trying to match file data and file names to a MIME type; I've written the [xdg-mime](https://crates.io/crates/xdg-mime) crate that implements the API to load and query that database. Since the database is externally updated, every user of xdg-mime will automatically be updated without requiring to be rebuilt.

Disclaimer: the xdg-mime crate API is still in [somewhat in flux](https://github.com/ebassi/xdg-mime-rs/releases/tag/0.1.0), but I'm happy to add new API to fit the requirements of applications like handlr. :wink:

**Comment by chmln** [comment]
Thats awesome @ebassi !
I have to say it looks quite compelling. Will take a look asap

**Comment by asm0dey** [comment]
@chmln you have typo on crae page: Documentation, not Dumentation
