### ISSUE TITLE
file not found when mime file doesn't exist

### ISSUE THREAD

**Issue by return127** [chmln/handlr#29]
Hi. I installed handlr from aur a few minutes ago and I would get this no matter what arguments i try.
Error: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
it was fixed when i created ~/.config/mimeapps.list

**Comment by chmln** [comment]
@return127 try updating to v0.5, the problem should be fixed now

**Comment by Kabouik** [comment]
I'm having a similar error when trying to open URLs with handlr, though the help suggests that `handlr open url` should be supported:

```
handlr open https://en.wikipedia.org
No such file or directory (os error 2)
```

What I am trying to do is change my default web browser from Firefox to Nyxt (using a `nyxt.desktop` file).
