### ISSUE TITLE
Unable to set x-scheme-handler

### ISSUE THREAD

**Issue by asm0dey** [chmln/handlr#4]
Please consider following example:

```
❯ handlr get x-scheme-handler/mailto
org.kde.kmail2.desktop
❯ handlr set x-scheme-handler/mailto /home/finkel/Desktop/mailto.desktop
error: Invalid value for '<handler>': no handler defined for this mime/extension
```

Here we expect that if we can query scheme handler — we should be able to set it too.
But it unexpectedly prints error (with some strange description).

**Comment by chmln** [comment]
Hi @asm0dey 

You need to place that `mailto.desktop` file in the `/home/finkel/.local/share/applications` folder, then run 

```sh
handlr set x-scheme-handler/mailto mailto.desktop
```

For reference, you can read https://wiki.archlinux.org/index.php/Desktop_entries#Application_entry

**Comment by asm0dey** [comment]
Still doesn't work:
```
❯ ls /home/finkel/.local/share/applications/mailto.desktop
/home/finkel/.local/share/applications/mailto.desktop
❯ handlr set x-scheme-handler/mailto mailto.desktop
error: Invalid value for '<handler>': badly-formatted desktop entry
```

**Comment by asm0dey** [comment]
That works, thank you!
