### ISSUE TITLE
Cannot set handler for mime application/x-ipynb+json

### ISSUE THREAD

**Issue by asparagii** [chmln/handlr#7]
I'm trying to set the handler for jupyter notebook files, whose mime type should be `application/x-ipynb+json`, but this happens:
```
$ handlr set application/x-ipynb+json jupyter-notebook.desktop 
error: Invalid value for '<mime>': invalid mime application/x-ipynb+json
```

I tried with `application/ipynb+json`, but I had the same results

**Comment by chmln** [comment]
@asparagii this will be fixed with v0.4 very soon
