### ISSUE TITLE
Does not fall back to mimetypes if directory name is of the format ___.___ 

### ISSUE THREAD

**Issue by OctarineSourcerer** [chmln/handlr#8]
I'd tried opening a path using handlr, it didn't work - the path was `/home/dan/.local/share/wesnoth/1.14/`. Other paths, such as `/home/dan`, opened fine, as the `inode/directory` mimetype is set to use Thunar.

Here's what I did to narrow down the issue - I hope that helps:
![image](https://user-images.githubusercontent.com/6842867/84514698-5a314500-acc3-11ea-96af-2e15e8e190c7.png)

It seems handlr thinks that the path provided is actually the path to a file, and so checks for existing extensions in its list. No matching one is exists, so it errors out, but doesn't check for if it has a mimetype handler.

It would also be worth checking for mimetype handlers before extensions - otherwise, with a directory of `/tmp/thing.pdf/`, it tries opening it with the handler for .pdf files, even though it's a directory/

**Comment by chmln** [comment]
Hi @OctarineSourcerer 

I've likewise bumped into weird edge-cases but I'm happy to say with v0.4.3 everything should be working properly.

Please give it a shot and let me know if the latest release fixes your issue.

**Comment by OctarineSourcerer** [comment]
Sorry it took me a couple days to reply! Just tested it, seems to work fine now for all above cases :) Thank you for the quick response!
